### PR TITLE
I created a command-line program that generates a random string that is N characters long.

### PR DESCRIPTION
**Pull request by NotNorom**
Hope you'll like it! :)

### CODE REVIEW

**Review by nzec — APPROVED** [review]
GOOD!

**Comment by joereynolds** [comment]
Hey @NotNorom,

I've added you to the CONTRIBUTORS.md file, thanks!

**Comment by nzec** [comment]
@joereynolds So, you really don't want anyone else committing in this repository, huh?

**Comment by joereynolds** [comment]
Hey @duttaditya18, 

What do you mean?
I'm migrating contributions over to a separate file so they don't clog up the main list of ideas. Otherwise it becomes too noisy

**Pull request closed without merging**
