### PR TITLE
Add a couple projects

### PR DESCRIPTION
**Pull request by KorySchneider**
Hi Joe,

I created a little [website](https://markfast.xyz) that simply hosts markdown files (might add a little more functionality in the future), and added a link to the idea list.

I also removed a bunch of trailing whitespace, and added a link to a vim plugin that I think was added a while ago but maybe got removed? Or maybe I forgot to submit the PR. Either way, thanks for your time and ideas!

### CODE REVIEW

**Review by nzec — APPROVED** [review]
LGTM! 👍

**Comment by joereynolds** [comment]
Hey Kory, I've removed all the 'CREATED by ...' annotations in the file, I was going to create a CREDITS.md file to put all of these in so they don't clog up the list.

Thanks for the PR, sorry for the late reply

**Comment by KorySchneider** [comment]
Hi Joe, no worries! Thanks for letting me know.

**Comment by joereynolds** [comment]
Hey Kory, 

I've created and added those to the file, thanks!
If there's any more, feel free to keep 'em comin'

**Pull request closed without merging**
